# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger: none

pool:
  vmImage: 'macos-latest'

variables:
  buildConfiguration: 'Release'
  system.debug: 'true'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: xamarinforms.sln

- bash: |
    # Set bundle '6_4_0', it contains Mono 6.4.0, Xamarin.Android 10.0
    SYMLINK="6_4_0"
    sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $SYMLINK
    MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
    #echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
    #echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
    echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
  displayName: Set latest Xamarin.Android and Mono

- task: XamarinAndroid@1
  displayName: 'Build Xamarin.Android project xamarinforms/xamarinforms.Android/xamarinforms.Android.csproj'
  inputs:
    projectFile: xamarinforms/xamarinforms.Android/xamarinforms.Android.csproj
    outputDirectory: '$(build.binariesdirectory)/$(BuildConfiguration)'
    configuration: '$(BuildConfiguration)'
    msbuildVersionOption: latest
    msbuildArchitectureOption: x64
    jdkVersionOption: 1.8

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.binariesdirectory)/$(BuildConfiguration)'
  condition: succeededOrFailed()
